// 11. Write a C program (we'll refer to it as A) that creates a child process B. Process B generates one random number N between 100 and 1000. Process A keeps generating and sending random numbers between 50 and 1050 to B until the absolute difference between the number generated by A and the number generated by B is less than 50. B prints the generated numbers and all the received numbers. A will print at the end the number of numbers generated until the stop condition was met.
// Example:
// Process B has generated 433
// B received 244; difference: 189
// B received 367; difference: 66
// B received 723; difference: 290
// B received 465; difference: 32
// Process A has generated 4 numbers  


#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>


int main(){
	int a2b[2], b2a[2];
	pipe(a2b); pipe(b2a);


	int f = fork();
	if(f == -1){
		perror("Error on fork");
		exit(1);
	}
	/// Process B
	else if(f == 0){
		close(a2b[1]); close(b2a[0]);	
		
		int n, nra, diff;
	//	time_t t;

	//	srand((unsigned) time(&t));
	//      srandom(time(0));
		srand(time(0));
		n=rand()%901 + 100;	
		printf("Process B generated %d\n", n);
	
		do{
			if(read(a2b[0], &nra, sizeof(int))<=0){
				perror("B cannot read from A");
                        	close(a2b[0]); close(b2a[1]);
				exit(2);
			}
			
			printf("B received %d; ", nra);
			
			if(nra > n)
				diff = nra-n;
			else
				diff = n-nra;
		
			if(write(b2a[1], &diff, sizeof(int))<=0){
				perror("B cannot send to A");
                                close(a2b[0]); close(b2a[1]);
                                exit(2);
			}
			printf("difference %d\n", diff);

		}while(diff>=50);

		close(a2b[0]); close(b2a[1]);
		exit(0);
	}

	/// Process A
	close(a2b[0]); close(b2a[1]);
	int nr, diff, c=0;
	//time_t t;
	do{
		//srand((unsigned) time(&t));
		//srand(time(NULL));
	//	srandom(time(0));

		srand(time(0));
		nr = rand()%1001 + 50;
		if(write(a2b[1], &nr, sizeof(int))<=0){
			perror("A cannot send to B");
			close(a2b[1]); close(b2a[0]);
			exit(2);			
		}
		c++;	
		if(read(b2a[0], &diff, sizeof(int))<=0){
			perror("A cannot send to B");
                        close(a2b[1]); close(b2a[0]);
                        exit(2);
		}
		
	}while(diff >= 50);
	
	close(a2b[1]); close(b2a[0]);
	wait(0);
	return 0;
}
